#!/bin/bash
for a in {1..10}
do
        echo kss $a
done


A=$(ls -a)
 echo $A
~                                                                                                                       ~                                                                                                                       ~                                                                                                                       ~            
